### ISSUE TITLE
This plugin swallowing actual build errors

### ISSUE THREAD

**Issue by sis-dk** [nonzzz/vite-plugin-compression#31]
# Bug report 🐞
Added the plugin as
```
compression({
	include: [/\.(js)$/],
	deleteOriginalAssets: true,
	algorithm: 'brotliCompress',
	filename: '[path][base].br',
}),
```
If any build error happens, this plugin seems to be taking it and printing a generic error:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'dist/assets/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/assets/index.js'
}
```

## Version & Environment
vite: "4.1.4"
vite-plugin-compression2: "0.9.2"

**Comment by nonzzz** [comment]
From the info your provide. I can know the error message it happening in `closeBundle` hook. Because 
`dist/assets/index.js` has side effect (with dynamic import). So the file will be read by filesystem.
But it can't find it. Only few info i can't guess more scenes who cause it. : ( @sis-dk

**Comment by nonzzz** [comment]
I guess it may be caused by the following reasons

- When build task is processing. The `dist/assets/index.js` has been deleted.
- This file is used by other threads or process.
- The directory `dist/assets` don't exist.

**Comment by sis-dk** [comment]
Hi @nonzzz, thanks for a details and quick response. I'll reproduce the issue and debug with the details you provided to find the exact cause in my case. Will update here.

**Comment by nonzzz** [comment]
Feedback is welcome if you find anything problem.

**Comment by jglee96** [comment]
I face this issue, and I made the reproduction [repo](https://github.com/jglee96/code-splitting-compression).

I think it caused by code splitting. In the reproduction I use [react-router lazy](https://reactrouter.com/en/main/route/lazy).
If I dont use lazy or disable deleteOriginalAssets and change filename, the issue doesn't reproduce.

The compression process looks like this.
```
file1 compress -> file1 delete -> file2 compress -> file2 delete -> file3 ....
```

If `file1` need `file2` it would be fail. (actually, it is just my guess)
Therefore compression process sholud be like this.
```
/* compression */
file1 compress -> file2 compress -> ...

/* delete origin assets*/
file1 delete -> file2 delete -> ...
```

**Comment by nonzzz** [comment]
@jglee96 Thanks for you repo

**Comment by nonzzz** [comment]
I find the problem. And fixed it in my local :)
I will test it.

**Comment by nonzzz** [comment]
Currently. I run all test success in my local. I will release a new version
