### ISSUE TITLE
threshold选项对某些js文件不生效

### ISSUE THREAD

**Issue by liuxiaofanRZ** [nonzzz/vite-plugin-compression#33]
# Bug report 🐞
配置如下
```js
compression({ threshold: 1024 * 80 })
```
但打包时小于80kb的js文件也被压缩了：
<img width="745" alt="image" src="https://github.com/nonzzz/vite-plugin-compression/assets/35593256/839429e8-1e72-41b9-973b-7dc896e9da50">

具体复现流程：`npm init vue@latest`创建项目，只选择vue-router功能，引入了本插件并设置threshhold为80*1024，然后build。

## Version & Environment
```json
{
  "dependencies": {
    "vue": "^3.3.4",
    "vue-router": "^4.2.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "vite": "^4.3.9",
    "vite-plugin-compression2": "^0.10.0"
  }
}
```

**Comment by nonzzz** [comment]
看起来确实是插件的问题。我会尽快进行修复感谢你的反馈

**Comment by nonzzz** [comment]
我对其进行了修复并且发布了`v0.10.1`. @liuxiaofanRZ

**Comment by liuxiaofanRZ** [comment]
非常感谢~
