### ISSUE TITLE
`deleteOriginalAssets` option removes `manualChunks`

### ISSUE THREAD

**Issue by ntltd** [nonzzz/vite-plugin-compression#35]
# Bug report 🐞

With this build config, the plugin seems to remove chunking strategy when using `deleteOriginalAssets` option:
```js
plugins: [
      react({
        fastRefresh: process.env.NODE_ENV !== 'test'
      }),
      compression({ deleteOriginalAssets: true })
    ],
build: {
      rollupOptions: {
        output: {
          manualChunks: function manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('lodash')) {
                return 'lodash'
              }
              if (id.includes('moment')) {
                return 'moment'
              }
              if (id.includes('leaflet')) {
                return 'leaflet'
              }
              if (id.includes('datadog')) {
                return 'datadog'
              }
              return 'vendor'
            }
            if (id.includes('components/icons')) {
              return 'icons'
            }
            if (id.includes('helpers/translations')) {
              return 'translations'
            }
          }
        }
      }
    }
```

Do you have an idea why?
Thanks

## Version & Environment

```json
"@vitejs/plugin-react": "^4.0.2",
"vite": "^4.4.0",
"vite-plugin-compression2": "^0.10.2",
```

## Expectation

Manual chunks should be generated:

<img width="487" alt="image" src="https://github.com/nonzzz/vite-plugin-compression/assets/16023275/27cdfea9-46a0-46d4-ba6d-fc95868854b8">

## Actual results (or Errors)

Manual chunks are not generated anymore:

<img width="485" alt="image" src="https://github.com/nonzzz/vite-plugin-compression/assets/16023275/1055c509-9823-42c0-b013-270652b8897e">

**Comment by nonzzz** [comment]
umm. Because you don't set `threshold` so the plugin will consume all `chunk`

**Comment by nonzzz** [comment]
as i can know. `manualChunks` also be consume in the full process. Have you generated the corresponding gz file locally?

**Comment by ntltd** [comment]
Not sure if `threshold` has to be set because I don't want to filter files by size.
If I disable `deleteOriginalAssets`, gz files of my chunks are generated. When I enable the option, they are delete at build.

**Comment by ntltd** [comment]
If I use the `compress()` plugin with `deleteOriginalAssets` turned off, it generates `lodash.js.gz` along `lodash.js` file:

<img width="184" alt="image" src="https://github.com/nonzzz/vite-plugin-compression/assets/16023275/231a5038-cf56-4820-9ec1-3d427c14f91c">


But if I turn on the option, the files are not generated anymore, the chunk seems to not be taken in account anymore.

**Comment by nonzzz** [comment]
jesus, i set the same option in my local but it can work well. I'm not sure what happened in your local :( . I think if you can provide a minimum repo is well.

**Comment by nonzzz** [comment]
By the way. the logo info is unreliable. When the chunk has side effect. It won't print out in your terminal. You should view the generated

**Comment by ntltd** [comment]
Yep, I tried to create a new repository with the same config, but it seems to work indeed: https://github.com/ntltd/vite-plugin-compression
I'm trying to figure out what's happening on the other repository 🤔

**Comment by ntltd** [comment]
Ok got it! It's not the same order on the prompt when I use the `deleteOriginalAssets` but compressed files are here 🙈 
Really sorry for disturbing and thanks for your amazing work!
