### ISSUE TITLE
need some help after compression success

### ISSUE THREAD

**Issue by morphiezy** [nonzzz/vite-plugin-compression#42]
Can someone guide me how to allow gz or br files to be loaded on a website? I have created a frontend project and I want to deploy it using Netlify. But there is a failure, files compressed using br cannot be loaded.  What should i do ?

![Screenshot 2023-10-30 120122](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/852f52e7-7eff-485e-a6e1-2078d9b292e8)
![image](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/49e107da-d423-4619-97f5-d96ca6cb4a99)

![image](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/95a09a8a-83d5-4f32-80c4-2467fca2616f)

**Comment by nonzzz** [comment]
You can take a look at [Gzip file serving](https://answers.netlify.com/t/gzip-file-serving/3445/31).
Like Github Pages or Netlify or Vercel will compress your chunk automatically. May be you won't need this plugin(Or remove option `deleteOriginalAssets`) . Or if you want to publish your website in other platform. Like amazon S3.( you can set `filename: '[path][base]'`

**Comment by morphiezy** [comment]
The first probem is solved, netlify can send response ```br``` file. But why the js file cannot be executed and render my component ? the preview of the file also blank. Do u have idea ? @nonzzz 

![image](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/9670594d-5e08-4210-9918-a3fc60f619d0)
![image](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/a8c4961f-1299-4f5a-83fe-e30e6e004209)

**Comment by nonzzz** [comment]
any log?

**Comment by morphiezy** [comment]
![image](https://github.com/nonzzz/vite-plugin-compression/assets/71913929/b1316594-aa68-446f-ae89-4bc9af007213)

now it's solved , thank for ur time @nonzzz
