### ISSUE TITLE
[tarball] robots.txt from public folder is not bundled

### ISSUE THREAD

**Issue by barrenechea** [nonzzz/vite-plugin-compression#51]
# Bug report 🐞

Hi! I was just trying to use this component, but I found a small issue for my use case.

## Version & Environment
vite-plugin-compression2 "^1.1.0"
Node.js v20.13.1, React project

## Expection
I'm storing a `robots.txt` file inside my `/public` folder. The file gets copied to the `/dist` folder when I run the build. I expect `robots.txt` to be bundled on the `dist.tar.gz` file, even if it's not being compressed.

## Actual results (or Errors)
The file is not included in the `dist.tar.gz` file.

**Comment by nonzzz** [comment]
Can you share your config or create an minimal reproduction

**Comment by barrenechea** [comment]
Here it is: https://stackblitz.com/edit/vitejs-vite-21q1mm?file=vite.config.ts

If I only run `plugins: [react(), tarball()]`, the files get properly bundled (it embeds the .txt and .svg).

If I run `plugins: [react(), compression(), tarball()]`, the .txt and .svg files are not bundled within the tarball.

**Comment by nonzzz** [comment]
It's really a bug. I forget sync the statics in some case. And currently about tarball is missing a full document.

**Comment by nonzzz** [comment]
Work at `v1.1.1`
