### ISSUE TITLE
Include `yaml`, `yml`, `toml` extensions in default regex

### ISSUE THREAD

**Issue by silverwind** [nonzzz/vite-plugin-compression#56]
# Feature request 🚀

Add additional text-based file formats to the default regex.

### Expected:

- No breaking changes

### Examples:

Change default regex to:

```js
/\.(html|xml|css|json|js|mjs|svg|yaml|yml|toml)$/
```

**Comment by nonzzz** [comment]
Pr welocme

**Comment by silverwind** [comment]
Okay, will try that later.
