### ISSUE TITLE
Export type `ViteWithoutCompressionPluginConfigFunction`?

### ISSUE THREAD

**Issue by silverwind** [nonzzz/vite-plugin-compression#58]
I had some issues typing a object that holds the options for this plugin:

```ts
const obj = {}; // which type?
const plugins = [compression(obj)];
```

I think the correct type for `obj` would be [`ViteWithoutCompressionPluginConfigFunction`](https://github.com/nonzzz/vite-plugin-compression/blob/475d8450759e7180c4c9b99ca0aed3ba3eb152a4/src/index.ts#L148) but this module currently does not export it.

Can it be exported? Possibly under a more memorable name?

**Comment by nonzzz** [comment]
Is there any scene about it? FWIW, Currently the `compress` method is defined with overloading. Therefore. this scene wasn't consideration when it was designed.

**Comment by silverwind** [comment]
My situation is that host all my plugin configs in a shared library, so there I no way I can call the plugin directly which is depended on in another repo.

**Comment by nonzzz** [comment]
Got it. So we should expose `ViteCompressionPluginConfigFunction` and `ViteWithoutCompressionPluginConfigFunction` and others etc? In past, I don't consider shared config. It's sounds well, PR welcome.

**Comment by silverwind** [comment]
I would suggest exporting under a short memorable name like `ViteCompressionPluginConfig`. I think the current overloads will need to be changed to a exportable type alias.

**Comment by nonzzz** [comment]
@mengdaoshizhongxinyang How do you think it.

**Comment by nonzzz** [comment]
If expose a new define function can be resolve this scene, I'll create a PR for it.

**Comment by silverwind** [comment]
FYI, I also had been experimenting with creating this type and had limited success with:

```ts
type ViteCompressionPluginConfig = Parameters<typeof compression>[0];
```

This works because `Parameters` uses the last overload. There is at least one problem with the type though that it does not accept `string` for `algorithm` for some reason:

```
index.ts:136:5 - error TS2322: Type 'string' is not assignable to type '(buf: InputType, options: undefined) => Promise<Buffer>'.

136     algorithm: "gzip",
        ~~~~~~~~~
```

**Comment by nonzzz** [comment]
In fact, Currently the overload declaration have some bug for it. A fix is wait for test. The overload will be retained, And we exported a declaration function and an optimized type.

**Comment by silverwind** [comment]
Regarding this `defineCompressionConfig` function: I guess it is one way to solve it. I would have preferred for my library to not have a runtime dependency on the plugin though because that library itself is built with vite and I want to keep that bundle size down.

**Comment by nonzzz** [comment]
We exported a new generic `ViteCompressionPluginOption`

**Comment by nonzzz** [comment]
Case

```ts

import type { ViteCompressionPluginOption, Algorithm } from 'vite-plugin-compression2'

const opt: ViteCompressionPluginOption<Algorithm> = { 
 // ...
}


```
