### ISSUE TITLE
ZSTD?

### ISSUE THREAD

**Issue by beckend** [nonzzz/vite-plugin-compression#60]
# Feature request 🚀

![image](https://github.com/user-attachments/assets/da32d56d-f296-4bec-af49-b4147d05183c)

Chromium

**Comment by nonzzz** [comment]
Any others? Aka, Currently plugin support custom  algorithm

**Comment by nonzzz** [comment]
```ts

import { compress } from '@mongodb-js/zstd'
import { compression } from 'vite-plugin-compression2'

compression<{ level: number }>({
  algorithm(buf, opt) {
    return compress(buf, opt)
  },
  compressionOptions: {
    level: 9
  }
})

```

**Comment by nonzzz** [comment]
Here is a simple usage. Can you have a try?

**Comment by nonzzz** [comment]
Oh, you should set filename option :)

**Comment by beckend** [comment]
Then it works ok, the types are a bit misleading.

**Comment by cheeeasy2501** [comment]
Good afternoon. Could you share a complete example of zstd integration for this plugin? 
It would also be great if someone would immediately give examples of compression integration for this library )

**Comment by nonzzz** [comment]
@cheeeasy2501  I'll move this issue to discussion
