### ISSUE TITLE
Plugin does not work with Vite V6

### ISSUE THREAD

**Issue by wichayapoka** [nonzzz/vite-plugin-compression#66]
# Bug report 🐞

Hi, Vite V6 just released today. I tried upgrade Vite to V6 and this plugin now does nothing. It no longer output the compressed files.

I noticed that in vite config file, I get this type error
`Type 'Plugin<any>' is not assignable to type 'PluginOption'.`

# Version & Environment
 vite-plugin-compression2 "^1.3.1"
 vite "^6.0.0"
 Node.js 22.11.0

**Comment by nonzzz** [comment]
I have released `v1.3.2`. Try it.

**Comment by wichayapoka** [comment]
Thanks. It works with Vite V6 now.

However, this now break build on Vite V5 and I got the same type error with
`"vite": "^5.4.11",
 "vite-plugin-compression2": "^1.3.2"`

If I force to install 1.3.1 it works fine on Vite V5.

**Comment by nonzzz** [comment]
Oh, I check my `package.json` i found i make mistake, now i move `vite` to `peerDependencies` it can work well :)

**Comment by wichayapoka** [comment]
Unfortunately, this will cause issue when start a new project with Vite template (at the moment use Vite V5) which does use `tsc -b` in the build scripts and will cause build error. 

Thanks for the second look.
